
default_cipher = {
    "a" : ["97"],
    "b" : ["98"],
    "c" : ["99"],
    "d" : ["100"],
    "e" : ["101"],
    "f" : ["102"],
    "g" : ["103"],
    "h" : ["104"],
    "i" : ["105"],
    "j" : ["106"],
    "k" : ["107"],
    "l" : ["108"],
    "m" : ["109"],
    "n" : ["110"],
    "o" : ["111"],
    "p" : ["112"],
    "q" : ["113"],
    "r" : ["114"],
    "s" : ["115"],
    "t" : ["116"],
    "u" : ["117"],
    "v" : ["118"],
    "w" : ["119"],
    "x" : ["120"],
    "y" : ["121"],
    "z" : ["122"]}

magenta_ornithopter_cipher = {
    "a" : ["frantic bannana"],
    "b" : ["Theodore", "theodore"],
    "c" : ["torque wrench"],
    "d" : ["underscore"],
    "e" : ["quality control supervisor"],
    "f" : ["quality control"],
    "g" : ["don't"],
    "h" : ["corn"],
    "i" : ["zoot suit"],
    "j" : ["Bill and Ted riding the zebra bareback"],
    "k" : ["cream cake"],
    "l" : ["rumble strip"],
    "m" : ["quincunx"],
    "n" : ["dormouse"],
    "o" : ["corncob"],
    "p" : ["riding"],
    "q" : ["mouse"],
    "r" : ["and"],
    "s" : ["country mouse"],
    "t" : ["undermine the fortifications"],
    "u" : ["town mouse"],
    "v" : ["zebra"],
    "w" : ["mortification of the flesh"],
    "x" : ["modular"],
    "y" : ["fortifications"],
    "z" : ["Jeremy Corbyn"]}
